version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - db:db
    ports:
      - "5000:5000"
    environment:
      - DB_URL=postgresql+psycopg2://postgres_user:password@db:5432/auto_company
    depends_on:
      - db
    command: >
      sh -c "sleep 10 && make run"
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: auto_company